[package]
name = "nominatim"
version = "0.3.0"
edition = "2018"
authors = ["Grant Handy <grantshandy@gmail.com>"]
repository = "https://github.com/grantshandy/nominatim-rs"
documentation = "https://docs.rs/nominatim"
description = "A reverse geocoding API client powered by openstreetmap."
keywords = ["async", "coordinates", "nominatim", "geocoding", "location"]
categories = ["api-bindings", "asynchronous"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.2"

[dev-dependencies]
tokio = { version = "1.20", features = ["full"] }