[package]
name = "nominatim"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2"
thiserror = "1"
serde_json = "1"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }